config/routes.rb
Rails.application.routes.draw do

  
  root "public#index"
  
  get 'admin', :to => 'access#index'

  get 'login', :to => 'access#login'
  
  match ':controller(/:action(/:id))', :via => [:get, :post]
  
  get ':permalink', :to => 'public#show'

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Simple CMS | <%= @page_title || "Admin" %></title>
	</head>
	<%= stylesheet_link_tag('application', :media => 'all') %>
	<%= javascript_include_tag('application') %>
<body>

<%# debug(params) %>
	
	<header>
		<h1>Simple CMS Admin</h1>
	</header>
	
	<content id="main">
		
		<% if !flash[:notice].blank? %> 
			<div class="notice">
				<%= flash[:notice] %>
			</div>
		<% end %>

		<div id="content">
			<!-- before yield -->
			<%= yield %>
			<!-- after yield -->
		</div>
	</content>
	<footer>
		<p class="copyright">&copy; Bart Hoekstra </p>
	</footer>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Simple CMS</title>
	</head>
	<body>

	<!-- before yield -->
	<%= yield %>
	<!-- after yield -->
	
	</body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Simple CMS <%= " | #{@page_title}" if @page_title %></title>
	</head>
	<%= stylesheet_link_tag('application', :media => 'all') %>
	<%= javascript_include_tag('application') %>
<body>

<%# debug(params) %>
	
	<header>
		<h1>Simple CMS</h1>
	</header>
	
	<%= link_to 'Admin panel', admin_path %>
	<%= link_to 'Login', login_path %>

	<content id="main">

		<div id="navigation">
		<ul>
			<% @subjects.each do |s| %>
				<li>
					<%= s.name %>
					<% if s.pages.size > 0 %>
					<ul>
						<% s.pages.each do |p| %>
							<li>
								<%= link_to p.name, p.permalink %>
							</li>
						<% end %>
					</ul>
					<% end %>
				</li>
			<% end %>
		</ul>
		</div>

		<div id="content">
			<!-- before yield -->
			<%= yield %>
			<!-- after yield -->
		</div>
		<div class="clear">
	</content>
	<footer>
		<p class="copyright">&copy; Bart Hoekstra </p>
	</footer>
</body>
</html>